import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "";

export const metadata: Metadata = {
  title: "UTokyo Qiskit Fall Fest 2025",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: `${basePath}/favicon/favicon.ico`, type: "image/x-icon" },
      { url: `${basePath}/favicon/favicon-16x16.png`, sizes: "16x16", type: "image/png" },
      { url: `${basePath}/favicon/favicon-32x32.png`, sizes: "32x32", type: "image/png" }
    ],
    apple: `${basePath}/favicon/apple-touch-icon.png`
  },
  manifest: `${basePath}/favicon/site.webmanifest`
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
